### ISSUE TITLE
Naming conflicts

### ISSUE THREAD

**Issue by p0l0us** [x821938/elog#2]
Log shortcuts like:
```
#define debug(logId, message, ...) logger.log(logId, DEBUG, message, ##__VA_ARGS__)
```

are breaking other libraries which uses keywords like `warning`, `debug`.

```
In file included from from src/main.cpp:31:
.pio/libdeps/.../ESP Async WebServer/src/ESPAsyncWebServer.h:280:19: error: macro "warning" requires 3 arguments, but only 1 given
     const String& ASYNCWEBSERVER_REGEX_ATTRIBUTE pathArg(size_t i) const;
```

I would suggest making those definitions optional and disabled by default. Putting them to separate header file could be flexible solution. So everyone can define own aliases header file if needed.

**Comment by romwam** [comment]
Same experience here when using library TinyGSM in the same project with elog.

**Comment by x821938** [comment]
I moved it into its own header now.
You can include them by:
#include <ElogMacros.h>

**Comment by x821938** [comment]
That should fix it - if not you can open another issue
